const books = [
  {
    id: 1,
    title: "NCERT Mathematics - Class 10",
    author: "NCERT",
    description: "Mathematics textbook for Class 10 published by NCERT, covering the CBSE curriculum.",
    price: 120.00,
    coverImage: "https://m.media-amazon.com/images/I/81+Eh-enKAL.jpg",
    category: "Mathematics",
    condition: "Good",
    seller: "Rahul Verma",
    isbn: "9788174507326",
    publishedDate: "2021",
    pages: 440,
    phone: "9876541230",
    email:"vaibhav",
    address:"BRRRRRRR",
  },
  {
    id: 2,
    title: "Concepts of Physics Vol. 1",
    author: "H.C. Verma",
    description: "A widely recommended physics book for JEE and school-level preparation.",
    price: 345.00,
    coverImage: "https://rukminim3.flixcart.com/image/850/1000/xif0q/book/8/s/b/concept-of-physics-by-h-c-verma-part-i-session-2024-25-original-imah5w7xcnvujg7y.jpeg?q=20&crop=false",
    category: "Physics",
    condition: "Like New",
    seller: "Ankita Sharma",
    isbn: "9788177091877",
    publishedDate: "2019",
    email:"vaibhav",
    address:"BRRRRRRR",
    pages: 462,
    phone: "9911223344"
  },
  {
    id: 3,
    title: "Objective Chemistry Vol. 1",
    author: "P. Bahadur",
    description: "Objective Chemistry for engineering and medical entrance exams.",
    price: 395.00,
    coverImage: "https://pictures.abebooks.com/isbn/9789350941263-us.jpg",
    category: "Chemistry",
    condition: "Excellent",
    seller: "Vikram Joshi",
    isbn: "9789352535041",
    publishedDate: "2020",
    email:"vaibhav",
    address:"BRRRRRRR",
    pages: 720,
    phone: "9800765432"
  },
  {
    id: 4,
    title: "NCERT Biology - Class 11",
    author: "NCERT",
    description: "Comprehensive biology book from NCERT for Class 11.",
    price: 135.00,
    coverImage: "https://rukminim2.flixcart.com/image/850/1000/xif0q/regionalbooks/4/t/v/ncert-biology-textbook-for-class-11th-original-imah2hfzdmtx4qmu.jpeg?q=90&crop=false",
    category: "Biology",
    condition: "Good",
    seller: "Nisha Patel",
    isbn: "9788174505124",
    publishedDate: "2021",
    email:"vaibhav",
    address:"BRRRRRRR",
    pages: 340,
    phone: "9123456789"
  },
  {
    id: 5,
    title: "Problems in General Physics",
    author: "I.E. Irodov",
    description: "Challenging problems in physics, often used for JEE Advanced preparation.",
    price: 280.00,
    coverImage: "https://m.media-amazon.com/images/I/51bNvwFPFqL._AC_UF1000,1000_QL80_.jpg",
    category: "Physics",
    condition: "Good",
    seller: "Rohit Yadav",
    isbn: "9789351414897",
    publishedDate: "2017",
    email:"vaibhav",
    address:"BRRRRRRR",
    pages: 400,
    phone: "9008765432"
  },
  {
    id: 6,
    title: "Modern ABC Chemistry - Class 12",
    author: "S.P. Jauhar",
    description: "A detailed and updated guide for Class 12 Chemistry students.",
    price: 499.00,
    coverImage: "https://m.media-amazon.com/images/I/61LozLrQFtL._AC_UF1000,1000_QL80_.jpg",
    category: "Chemistry",
    condition: "Excellent",
    seller: "Priya Rathi",
    isbn: "9789388740177",
    publishedDate: "2022",
    pages: 896,
    email:"vaibhav",
    address:"BRRRRRRR",
    phone: "9988776655"
  }
];

export default books;
